from games.TicTacToe import Game
from networks.TicTacToe import Net

EXPERIMENT_NAME = 'TicTacToe_2ResBlocks'
GAME = Game()
NETWORK = Net(RES_BLOCKS=2)
C_PUCT = 1.
NUMBER_OF_MINIBATCHES=70000
LEARNING_RATE_POLICY_STRING = 'lambda minibatch: 0.01 if minibatch < 40000 else 0.001 if minibatch < 60000 else 0.0001'
MINIBATCH_SIZE = 128
GAMES_BETWEEN_VERSIONS = 15
MINIBATCHES_BETWEEN_VERSIONS = 5
SNAPSHOT_PERIOD = 100
SELECTION_LOOKBACK_SPAN = 2000
INDEPENDENT_SIMULATION_POLICY = True
ROLLOUTS_PER_MOVE = 25
DIRICHLET_PARAMETER = 10
EPSILON = 0.25
MCST_MINIBATCH_SIZE = 8
MAXIMUM_SIMULATION_DEPTH = 10
TAO_FUNCTION_STRING = 'lambda depth: 1.0 if depth < 2 else 0.0'